/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-03-29 17:20:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class QTKH_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Quản trị Khách Hàng</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"container\">\r\n");
      out.write("    <div > \r\n");
      out.write("        <img src=\"images/Banner4.jpg\" width=\"100%\"  alt=\"...\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("        <ul class=\"nav nav-tabs\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\" >Admin Client</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"/views/admin/QTNV.jsp\">Administrative Staff</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("          </li>\r\n");
      out.write("     \r\n");
      out.write("        </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"card mt-4 mb-5 ms-5 me-5 \">\r\n");
      out.write("    <div class=\"ms-5 me-5 mt-3\">\r\n");
      out.write("      <div class=\"row\">    <label class=\"text-center fs-4 text-danger fw-bold\">Quản trị Khách Hàng</label></div>\r\n");
      out.write("      <form action=\"AdminServlet\" method=\"post\" >\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"exampleInputIdNV1\" class=\"form-label\">ID_NV</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"exampleInputIdNV1\" >\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"exampleInputHoTen1\" class=\"form-label\">HOTEN</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"exampleInputHoTen1\" >\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label class=\"form-label\">GioiTinh</label>\r\n");
      out.write("              <div class=\"col-sm-1\"> <input type=\"radio\" value=\"0\"> Nam </div>  \r\n");
      out.write("              <div class=\"col-sm-1\"><input type=\"radio\"  value=\"1\">  Nữ</div>\r\n");
      out.write("              <div class=\"col-10\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"exampleInputEmail1\" class=\"form-label\">Email</label>\r\n");
      out.write("              <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" >\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"exampleInputPhone1\" class=\"form-label\">Số điện thoại</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"exampleInputPhone1\" >\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"exampleInputDiaChi1\" class=\"form-label\">Địa Chỉ</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"exampleInputDiaChi1\" >\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-1\"> \r\n");
      out.write("               <button type=\"submit\" class=\"btn btn-outline-info text-primary mb-3\" value=\"0\">Create</button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-1\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-outline-info text-primary mb-3\" value=\"1\">Update</button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-1\">    \r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-outline-info text-primary mb-3 ms-2\" value=\"2\">Delete</button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("  </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("    <table class=\"table table-danger\">\r\n");
      out.write("      <thead>\r\n");
      out.write("        <th> ID_NV</th>\r\n");
      out.write("        <th> HOTEN</th>\r\n");
      out.write("        <th> GioiTinh</th>\r\n");
      out.write("        <th>Email </th>\r\n");
      out.write("        <th> Password</th>\r\n");
      out.write("        <th> SĐT</th>\r\n");
      out.write("        <th> DiaChi</th>\r\n");
      out.write("      </thead>\r\n");
      out.write("\r\n");
      out.write("      <tbody>\r\n");
      out.write("        <tr>\r\n");
      out.write("\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("      </tbody>\r\n");
      out.write("   </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/jquery.min.js\"> </script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"> </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
