package demo2;

public class demo7 {
	public static void main(String[] args) {
		String sqlString = "CREATE table `admins`\r\n"
				+ "(\r\n"
				+ "    id_AD int AUTO_INCREMENT not null,\r\n"
				+ "    hoTen text not null,\r\n"
				+ "    diaChi text,\r\n"
				+ "    email text, \r\n"
				+ "    sdt text,\r\n"
				+ "    PRIMARY key(id_AD)\r\n"
				+ "    );\r\n"
				+ "    \r\n"
				+ "    \r\n"
				+ "    \r\n"
				+ "    CREATE table `staffs`\r\n"
				+ "(\r\n"
				+ "    id_NV int AUTO_INCREMENT not null,\r\n"
				+ "    id_AD int not null,\r\n"
				+ "    hoTen text(50) not null,\r\n"
				+ "    gioiTinh text(10) not null,\r\n"
				+ "    email text(50), \r\n"
				+ "    sdt text(10),\r\n"
				+ "    diaChi text(100),\r\n"
				+ "    trangThai int,\r\n"
				+ "    PRIMARY key (id_NV)\r\n"
				+ "    );\r\n"
				+ "    \r\n"
				+ "    CREATE table `customers`\r\n"
				+ "(\r\n"
				+ "    id_KH int AUTO_INCREMENT not null,\r\n"
				+ "    id_NV int not null,\r\n"
				+ "    hoten text(50) not null,\r\n"
				+ "    gioiTinh text(10) not null,\r\n"
				+ "    email text(50), \r\n"
				+ "    password varchar(\r\n"
				+ "    sdt text(10),\r\n"
				+ "    diaChi text(100),\r\n"
				+ "    trangThai int,\r\n"
				+ "    PRIMARY key (id_KH)\r\n"
				+ "    );\r\n"
				+ "    \r\n"
				+ "    CREATE table `bills`\r\n"
				+ "(\r\n"
				+ "    id_B int AUTO_INCREMENT not null,\r\n"
				+ "    id_SP int  not null,\r\n"
				+ "    id_KH int  not null,\r\n"
				+ "    hoTen text(50) not null,\r\n"
				+ "    gioiTinh text(10) not null,\r\n"
				+ "    email text(50), \r\n"
				+ "    sdt text(10),\r\n"
				+ "    diaChi text(100),\r\n"
				+ "    trangThai int,\r\n"
				+ "    PRIMARY key (id_B)\r\n"
				+ "    );\r\n"
				+ "    \r\n"
				+ "    CREATE table `products`\r\n"
				+ "(\r\n"
				+ "    id_SP int AUTO_INCREMENT not null,\r\n"
				+ "    id_NV int not null,\r\n"
				+ "    ten_SP text(50) not null,\r\n"
				+ "    gia float not null,\r\n"
				+ "    soLuong int not null, \r\n"
				+ "    moTa text(500),\r\n"
				+ "    PRIMARY KEY(id_SP)\r\n"
				+ "    );\r\n"
				+ "\r\n"
				+ "alter TABLE `admins` ADD COLUMN password text(32) not null;\r\n"
				+ "alter TABLE `staffs` ADD COLUMN password text(32) not null;\r\n"
				+ "alter TABLE `customers` ADD COLUMN password text(32) not null;\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    alter TABLE `products` add FOREIGN key (id_KH) REFERENCES`customers`(id_KH);";
		
		
		System.out.println(sqlString.toLowerCase());
	}
}
